import { describe, expect, it } from "vitest";
import {
  syntheticPassport,
  syntheticRegressionFixtures,
  syntheticReviewRule,
} from "../../../test/helpers/matrix-review-fixture.js";
import type { CompositeEvaluationContext } from "./composite-comparison.js";
import { runRuleRegression } from "./matrix-regression.js";
import {
  regressionEngines,
  validateRegressionInput,
  type RegressionFixture,
} from "./matrix-review-contract.js";

const context: CompositeEvaluationContext = {
  context_id: "synthetic-context",
  scope_key: "synthetic-scope",
  period_key: null,
  reference: { document_id: "synthetic-pd", revision_id: "pd-v1" },
  actual: { document_id: "synthetic-rd", revision_id: "rd-v1" },
  applicability: "applicable",
  applicability_basis:
    "Manual synthetic applicability; not an actual project or norm",
};
function setup() {
  const rule = {
    ...syntheticReviewRule,
    comparison: {
      kind: "composite",
      schema_version: 1,
      root: {
        id: "root",
        kind: "and",
        children: [
          {
            id: "first",
            kind: "scalar",
            comparison: syntheticReviewRule.comparison,
          },
          {
            id: "second",
            kind: "scalar",
            comparison: syntheticReviewRule.comparison,
          },
        ],
      },
    },
  };
  const passport = syntheticPassport();
  const scalar = passport.branches[1]!;
  passport.branches = [
    passport.branches[0]!,
    { ...scalar, id: "first" },
    { ...scalar, id: "second" },
    {
      ...scalar,
      id: "root",
      operator: "composite",
      version: regressionEngines.composite,
      basis_required: true,
      basis: {
        reference: "Synthetic AND rule, not a Matrix interpretation",
        version: "1",
        locator: "composite-regression.test.ts",
        valid_from: null,
        valid_to: null,
      },
    },
  ];
  const original = syntheticRegressionFixtures();
  const fixtures: RegressionFixture[] = original.filter(
    (f) => f.branch_id === "extraction",
  );
  for (const fixture of original.filter((f) => f.branch_id === "comparison")) {
    for (const id of ["first", "second", "root"]) {
      const item = structuredClone(fixture);
      item.id = `${id}-${item.category}`;
      item.branch_id = id;
      if (id === "root") {
        item.context = structuredClone(context);
        item.inputs = item.inputs.map((input) => {
          const ref =
            input.role === "expected" ? context.reference! : context.actual!;
          return {
            ...input,
            ...ref,
            comparison_context: {
              context_id: context.context_id,
              scope_key: context.scope_key,
              period_key: context.period_key,
            },
          };
        });
        const result =
          item.category === "positive"
            ? "false"
            : item.category === "uncertain"
              ? "unknown"
              : "true";
        item.expected.verdict =
          result === "true"
            ? "match"
            : result === "false"
              ? "discrepancy"
              : "not_comparable";
        // Hand-authored oracle from fixture values; never generated by evaluator.
        item.expected.composite = {
          result,
          branches: ["root", "first", "second"].map((id) => ({
            id,
            result,
            evaluated: true,
          })),
        };
      }
      fixtures.push(item);
    }
  }
  return { rule, passport, fixtures };
}

describe("MAT gate for scalar composite branches (synthetic only)", () => {
  it("runs the existing extraction/scalar evaluators and asserts every branch in the server report", () => {
    const { rule, passport, fixtures } = setup();
    const validated = validateRegressionInput({ schema_version: 1, fixtures });
    const report = runRuleRegression(rule, passport, validated);
    expect(report.blockers).toEqual([]);
    expect(report.cases.flatMap((c) => c.errors)).toEqual([]);
    expect(report.passed).toBe(true);
    expect(
      report.cases.find((c) => c.id === "root-uncertain")?.actual.composite
        ?.root.children[1]?.scalar?.status,
    ).toBe("actual_missing");
    expect(report.engines.composite).toBe("composite-scalar-v1");
    expect(report.quality.corpus_accuracy).toBeNull();
    expect(runRuleRegression(rule, passport, validated)).toEqual(report);
  });
  it("cannot approve a tree without root logic basis, leaf coverage or current operator version", () => {
    const { rule, passport, fixtures } = setup();
    passport.branches.find((b) => b.id === "root")!.basis = null;
    passport.branches.find((b) => b.id === "first")!.version =
      "comparison-engine-v3";
    const report = runRuleRegression(
      rule,
      passport,
      fixtures.filter((f) => f.id !== "second-uncertain"),
    );
    expect(report.blockers).toEqual(
      expect.arrayContaining([
        "root:unknown_basis",
        "first:unsupported_operator_version",
        "second:missing_uncertain",
      ]),
    );
    expect(report.passed).toBe(false);
    passport.branches = passport.branches.filter((b) => b.id !== "second");
    expect(runRuleRegression(rule, passport, fixtures).blockers).toContain(
      "second:comparison_branch_missing",
    );
  });
  it("rejects forged, missing or incomplete tree assertions even when the top verdict matches", () => {
    for (const attack of [
      "missing",
      "result",
      "branch",
      "evaluated",
    ] as const) {
      const { rule, passport, fixtures } = setup();
      const fixture = fixtures.find((f) => f.id === "root-negative")!;
      if (attack === "missing") delete fixture.expected.composite;
      if (attack === "result")
        fixture.expected.composite!.branches[1]!.result = "unknown";
      if (attack === "branch") fixture.expected.composite!.branches.pop();
      if (attack === "evaluated")
        fixture.expected.composite!.branches[1]!.evaluated = false;
      const report = runRuleRegression(rule, passport, fixtures);
      expect(report.passed).toBe(false);
      expect(report.cases.find((c) => c.id === fixture.id)?.errors).toContain(
        "composite_trace_assertion_failed",
      );
    }
  });
  it("server computation blocks a forged context and records the reason rather than trusting expected truth", () => {
    const { rule, passport, fixtures } = setup();
    const fixture = fixtures.find((f) => f.id === "root-negative")!;
    fixture.inputs[1]!.comparison_context!.scope_key = "other-element";
    const report = runRuleRegression(rule, passport, fixtures);
    expect(report.passed).toBe(false);
    const actual = report.cases.find((c) => c.id === fixture.id)!.actual;
    expect(actual.verdict).toBe("not_comparable");
    expect(actual.composite?.root.reasons).toContain(
      "composite_member_context_mismatch",
    );
  });
  it("schema rejects fake context keys, missing applicability basis and duplicate branch assertions", () => {
    for (const attack of ["context", "basis", "duplicate"] as const) {
      const { fixtures } = setup();
      const fixture = fixtures.find((f) => f.id === "root-negative")!;
      if (attack === "context")
        (fixture.context as unknown as Record<string, unknown>).extra = true;
      if (attack === "basis") fixture.context!.applicability_basis = null;
      if (attack === "duplicate")
        fixture.expected.composite!.branches[1]!.id = "root";
      expect(() =>
        validateRegressionInput({ schema_version: 1, fixtures }),
      ).toThrow();
    }
  });
  it("recognizes an unknown OR branch as uncertainty even when another branch determines true", () => {
    const { rule, passport, fixtures } = setup();
    rule.comparison.root.kind = "or";
    rule.comparison.root.children[1]!.comparison = {
      kind: "ordered_category",
      direction: "no_decrease",
      map_version: "synthetic-v1",
      ranks: { A: 1, B: 2 },
      basis: {
        reference: "Synthetic labels only",
        version: "1",
        locator: "test",
      },
    };
    const fixture = fixtures.find((f) => f.id === "root-negative")!;
    fixture.category = "uncertain";
    fixture.expected.composite = {
      result: "true",
      branches: [
        { id: "root", result: "true", evaluated: true },
        { id: "first", result: "true", evaluated: true },
        { id: "second", result: "unknown", evaluated: true },
      ],
    };
    const report = runRuleRegression(rule, passport, fixtures);
    const tested = report.cases.find((c) => c.id === fixture.id)!;
    expect(tested.actual.verdict).toBe("match");
    expect(tested.actual.composite?.root.children[1]?.result).toBe("unknown");
    expect(tested.errors).toEqual([]);
    // This intentionally mixed synthetic plan still has independent policy /
    // category failures; one correct branch projection cannot approve it.
    expect(report.passed).toBe(false);
  });
});
